---
- hosts: stapp02
  become: true
  tasks:
          - name: create a cron job
            yum:
                    name: cronie
                    state: present

          - name: start the cron job
            systemd:
                    name: crond
                    state: started
                    enabled: yes
         
          - name: Creates a cron file under /etc/cron.d
            cron:
                    minute: "*/5"
                    user: root
                    job: "echo hello > /tmp/cron_text"

