---
- hosts: stapp01
  become: true
  tasks:
          - name: archive the directory and move to home 
            archive:
                    path: /data/siva
                    dest: /home/siva.tar.gz

